require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'coverage/**/*'
    - 'tmp/**/*'
    - '*.gemspec'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'Rakefile'

Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Max: 300

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

