#!/usr/bin/env ruby
# frozen_string_literal: true

begin
  if ARGV[0] == "new" && ARGV[1]
    app_name = ARGV[1]

    require "static_site_builder"

    generator = StaticSiteBuilder::Generator.new(app_name)
    generator.generate
  else
    puts "Usage: static-site-builder new <app-name>"
    exit 1
  end
rescue Interrupt
  puts "\n\nGeneration cancelled."
  exit 1
end
